#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

foamListTimes -rm
rm -r processor*

decomposePar
mpirun -np 8 pimpleMechanoChemFoam -parallel


# ----------------------------------------------------------------- end-of-file
